### PR TITLE
Update hanoi-basic.c

### PR DESCRIPTION
**Pull request by teibit**
In this version, I have tried to develop the first part of the program. It Is extensively commented so you should be able to follow it. 

Basically, what I have done is create a function called menu that prints some explanatory headers of the program and, depending on what the user (who is following the instructions) introduces, some things happen or not. The goal of this function is to create a "first step" in which the user can start interacting with the program by giving commands to the console. 

Unfortunately, it currently does not work. It shows an error on Xcode on line 83 but I don't understand how to fix it. Besides that, no more warnings.

Please, take a deep and long look at it and between you two Jorge and Laura fix this problem or come up with a restructurization that will address the problem from another angle.

Thank you! 🙏

### CODE REVIEW

**Comment by lauramolina13** [comment]
Add \n\n at line 69. In Netbeans it doesn't show any error at line 83

**Comment by teibit** [comment]
Why the \n\n? I don't think it's needed.

**Comment by lauramolina13** [comment]
If not,  the lines 69 and 71 overlap. Like this: -o specifies the writting operation to be used to create the fileThe available commands are the following:

**Comment by teibit** [comment]
You're right. Fixed! Now let's figure out why when I type hanoiplus + enter the program stops executing. Please, @lauramolina13 @jicruz work on that.

**Pull request merged**
